### ISSUE TITLE
Could not initialize class com.pty4j.unix.PtyHelpers

### ISSUE THREAD

**Issue by atari83** [JetBrains/pty4j#24] opened 2015-12-18 17:14 UTC
Hello there,
I'm using CLion 1.2 on FreeBSD 10.2 amd64.
The problem is when I want to debug a program, it will raise an error which says:
Could not initialize class com.pty4j.unix.PtyHelpers

and debugging will stop ..

**Comment by c0d1f1ed** [comment] 2016-11-02 14:41
I have the same issue with CLion 2016.2.3 on an ARM64 system.

Does anyone know what might be the cause?

**Comment by stigger** [comment] 2016-11-02 14:43
CLion does not support freebsd and ARM64 systems. You can try building the native pty4j binaries for your platform yourself.

**Comment by c0d1f1ed** [comment] 2016-11-02 15:00
For not supporting it, it runs pretty well. :-) Just haven't gotten the debugger to work yet.

I'd love to try building pty4j myself, but I haven't found any build instructions anywhere...

**Comment by stigger** [comment] 2016-11-02 15:01
There are a bunch of makefiles in the native/ dir, they are pretty straightforward.

**Comment by c0d1f1ed** [comment] 2016-11-02 15:39
Thanks! I have an ARM64 libpty.so now. Where should I put it for CLion to use it?

**Comment by stigger** [comment] 2016-11-02 15:46
Probably it's going to be <clion>/lib/libpty/linux/x86_64.

**Comment by c0d1f1ed** [comment] 2016-11-02 19:52
I've tried that and all the other lib directories, but no luck. I'll see if using LD_DEBUG=libs will make me any wiser...

**Comment by stigger** [comment] 2016-11-02 20:03
You can try this: add `jna.debug_load=true` to bin/idea.properties, then launch CLion from a terminal and look in the logs for a path where CLion expects to find a library.

**Comment by c0d1f1ed** [comment] 2016-11-02 20:39
Smoking gun:

[     72]  ERROR -        #com.intellij.idea.Main - Unable to load JNA library (OS: Linux 3.10.96-tegra) 
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path (./../lib/bootstrap.jar:./../lib/extensions.jar:./../lib/util.jar:./../lib/jdom.jar:./../lib/log4j.jar:./../lib/trove4j.jar:./../lib/jna.jar)

**Comment by stigger** [comment] 2016-11-02 20:43
What's the full output?

**Comment by c0d1f1ed** [comment] 2016-11-02 20:58
Looking in classpath from com.intellij.util.lang.UrlClassLoader@368102c8 for /com/sun/jna/linux-aarch64/libjnidispatch.so
[     47]  ERROR -        #com.intellij.idea.Main - Unable to load JNA library (OS: Linux 3.10.96-tegra) 
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path (./../lib/bootstrap.jar:./../lib/extensions.jar:./../lib/util.jar:./../lib/jdom.jar:./../lib/log4j.jar:./../lib/trove4j.jar:./../lib/jna.jar)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:776)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
	at com.sun.jna.Native.<clinit>(Native.java:131)
	at com.intellij.idea.StartupUtil.c(StartupUtil.java:349)
	at com.intellij.idea.StartupUtil.prepareAndStart(StartupUtil.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl.start(MainImpl.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.ide.plugins.PluginManager.a(PluginManager.java:90)
	at java.lang.Thread.run(Thread.java:745)

**Comment by c0d1f1ed** [comment] 2016-11-07 19:10
Made a bit of progress. I built JNA myself and it produced a libjnidispatch.so which I added to CLion's jna.jar using "jar uf jna.jar /com/sun/jna/linux-aarch64/libjnadispatch.so". The error that libjnidispatch.so is not found is now gone.

But now I'm getting:
[     79]  ERROR -        #com.intellij.idea.Main - Unable to load JNA library (OS: Linux 3.10.96-tegra) 
java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native

I verified that the library does export a fromNative function with "nm -D", so I'm not sure what's wrong...

**Comment by matthiasblaesing** [comment] 2016-11-07 19:54
@c0d1f1ed  you posted into an android bug. Be careful when building the JNA native part. The native part and JNA core are tightly coupled. You'll need a matching version. I build the JNA libraries for JNA master and the unittests run clear.

So I suggest: Choose if you want to test JNA 4.2.2 or master (the upcoming 4.3 version, at work I had to push this into production and I'm happy with it), run a full build and test cycle (ant clean; ant test; ant dist). There are two unittests, you can safely ignore:

- testLoadAndUnloadFromJAR (timing)
- testLoadLibraryWithUnicodeName (environment with an old java version)

Make sure there are _no_ other JNA jars on your classpath.

**Comment by c0d1f1ed** [comment] 2016-11-07 21:31
Ah, I see, dispatch.c is compiled into libjnidispatch.so and looks for methods in Native.java, which has to be a matching version. Thanks for clarifying that!

I tried replacing CLion's entire jna.jar with my build (master, all tests pass), and the fromNative error is gone, but now CLion is unable to access the file system (i.e. when I click Open Project it doesn't show any paths or files). CLion's original jna.jar doesn't have that problem, but has the above issue.

In the terminal output I get:
"java.io.IOException: /home/ubuntu/.CLion2016.2/config/options not found"
But that directory does exist.

**Comment by matthiasblaesing** [comment] 2016-11-07 22:02
Sorry - can't help further. I don't know what CLion does internally, they might have decided to either depend on changed features or modified the bindings. That would be the moment to turn to JetBrains and get an updated JNA build.

Maybe you can get the exact version if JNA used, checkout that version from git and build that and only use the jna package. (check which JNA jars you deleted and restore the original configuration, you have to make sure, that only on jar provides the jnidispatch library and the Native class).

**Comment by stigger** [comment] 2016-11-07 22:08
@c0d1f1ed Have you tried [EAP builds](https://confluence.jetbrains.com/display/CLION/Early+Access+Program) of CLion? They contain an updated jna.jar with aarch64 version of libjnidispatch.so included.

**Comment by c0d1f1ed** [comment] 2016-11-15 16:52
@stigger Thanks for the suggestion. Unfortunately the EAP build has the same symptom of not being able to open any files. Anyway, I've started using Nemiver for debugging instead.

**Comment by v00d00** [comment] 2017-08-10 19:38
Still the case with CLion 2017.2

**Comment by berserkrambo** [comment] 2017-10-02 14:54
I was able to get the debugger running on a Jetson TX2 (ARM64).
I simply had to build the native library libpty.so for my system.

1) Identify which version of ptyj4 is used by clion. I checked inside clion-2017.1.2/lib and found pty4j-0.7.1.jar, so the version was 0.7.1 for me.

2) Clone ptyj4 repository and checkout to a commit with the specified version. There is no tag or branch, so I had to find them manually by browsing commits. In my case was 1f9db6dbf790f85e7eb9a2f8beabb6b684946186

3) Browse ptyj4/native folder and copy Makefile_linux to Makefile, then edit it by removing all rows pertaining x86 architecture (we just need aarch64)

Here is my version of the Makefile:
[Makefile.zip](https://github.com/traff/pty4j/files/1349257/Makefile.zip)

4) Build with make -j6

5) Copy pty4j/os/linux/x86_64/libpty.so to clion-2017.1.2/lib/libpty/linux/x86_64/libpty.so

Now the debugger should be working :)
I'm not sure that the version has to be the same as the one in CLion, but it doesn't hurt.

**Comment by hardsetting** [comment] 2017-10-02 14:57
I was able to get the debugger running on a Jetson TX2 (ARM64).
I simply had to build the native library libpty.so for my system.

1) Identify which version of ptyj4 is used by clion. I checked inside clion-2017.1.2/lib and found pty4j-0.7.1.jar, so the version was 0.7.1 for me.

2) Clone ptyj4 repository and checkout to a commit with the specified version. There is no tag or branch, so I had to find them manually by browsing commits. In my case was 1f9db6dbf790f85e7eb9a2f8beabb6b684946186

3) Browse ptyj4/native folder and copy Makefile_linux to Makefile, then edit it by removing all rows pertaining x86 architecture (we just need aarch64)
Here is my version: [Makefile.zip](https://github.com/traff/pty4j/files/1349257/Makefile.zip)

4) Build with make -j6

5) Copy pty4j/os/linux/x86_64/libpty.so to clion-2017.1.2/lib/libpty/linux/x86_64/libpty.so

Now the debugger should be working :)
I'm not sure that the version has to be the same as the one in CLion, but it doesn't hurt.

**Comment by marikhu** [comment] 2018-09-22 07:16
its pty4j ... typo in above comment, and am trying the fix specified by hardsetting.. hoping it will work :)

**Comment by xuhaoda1995** [comment] 2018-12-14 01:36
@hardsetting now i'm using clion latest version 2018.3.1, i followed your step but in the last step i found my  clion folder didn't have libpty.so. there are only x.jar files in the clion-x.x.x/lib . i also searched the file in all clion folder but no file found

**Comment by floriangeis** [comment] 2018-12-18 14:36
@xuhaoda1995 Try to replace the existing libpty.so in the pty4j-0.8.5.jar file (I used the ubuntu archive manager) with your compiled one (following hardsetting) in this directory: /resources/com/pty4j/native/linux/x86_64/. After rebooting my DPX2 debugging is working properly. Thanks also to @hardsetting

**Comment by xuhaoda1995** [comment] 2018-12-24 08:01
I have solved the problem by installing the old version 2017,I found there existing the libpty.so in 2017 version folder. Then I followed @hardsetting way and found it running well when debug.  Anyway thanks @floriangeis for answering and the method of @hardsetting .

**Comment by segrey** [comment] 2018-12-25 09:18
Please file a separate issue regarding AArch64 support. Would like to hear your use cases to prioritize it.
This issue is pretty old, and should probably be closed.

**Closed** 2019-01-03 20:32 UTC
