### ISSUE TITLE
Can not build project

### ISSUE THREAD

**Issue by jackcomtw** [JetBrains/pty4j#130] opened 2022-11-29 09:03 UTC
that's terrible

your dependencies jar purejavacomm
he disappeared into this world 
XD

mvn clean package

[INFO] Scanning for projects...
[INFO]
[INFO] ----------< StreamingPlatform >-----------
[INFO] Building StreamingPlatform 
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.jetbrains.pty4j:purejavacomm:jar:0.0.11.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.048 s
[INFO] Finished at: 2022-11-29T16:36:58+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project StreamingPlatform: Could not resolve dependencies for project StreamingPlatform:jar:20221129-216: Failure to find org.jetbrains.pty4j:purejavacomm:jar:0.0.11.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by PakhomovAlexander** [comment] 2022-12-08 14:34
Looks like https://jcenter.bintray.com/ does not allow to get the artifact from there. 

Maintainers, do you have any plans to update the repository for the purejavacomm  library? 

Thanks.

**Comment by jackcomtw** [comment] 2022-12-09 06:06
> Looks like https://jcenter.bintray.com/ does not allow to get the artifact from there.
> 
> Maintainers, do you have any plans to update the repository for the purejavacomm library?
> 
> Thanks.

No ~ I have not any plans, and I abandon use pty4j , Because I have project time pressure.
sorry

**Comment by segrey** [comment] 2022-12-09 09:53
Workaround: add `https://packages.jetbrains.team/maven/p/ij/intellij-dependencies` repository.

Maven
```
  <repositories>
    <repository>
      <id>jetbrains-intellij-dependencies</id>
      <url>https://packages.jetbrains.team/maven/p/ij/intellij-dependencies</url>
    </repository>
  </repositories>
```
Gradle
```
repositories {
    maven {
        url "https://packages.jetbrains.team/maven/p/ij/intellij-dependencies"
    }
}
```

For example, here is [jediterm configuration](https://github.com/JetBrains/jediterm/blob/master/pty/build.gradle#L9-L13). I'm looking into ways to get rid of such workaround.

**Comment by PakhomovAlexander** [comment] 2022-12-09 14:46
@segrey thank you for the response. Unfortunately, there are some projects that could not use a custom maven repository for those dependencies.

Do you have any plans to publish `purejavacomm` to the maven central?

**Comment by agorgl** [comment] 2023-05-22 10:07
Bumped into this too, when trying to use pty4j as a clojure dependency, can somebody fix this?

**Comment by sureshg** [comment] 2024-02-05 22:53
Would be great if you can fix this. Custom maven repo is no go for many enterprises, so currently there is no clean way to resolve the `purejavacomm` dependency (without doing some gradle compose build magic). The dependency graph is broken and tools like deps.dev clearly shows this warning https://deps.dev/maven/org.jetbrains.pty4j%3Apty4j/0.12.25 . The correct way is to fix this is to publish `purejavacomm`  to maven central.

**Comment by dave-griffiths** [comment] 2024-07-08 08:29
Just came across the same. Surprised it is published in maven central if unusable.

**Comment by segrey** [comment] 2024-10-07 09:34
Duplicate of #121

**Comment by segrey** [comment] 2024-10-07 09:34
Since pty4j 0.13.0, there is no longer dependency on `purejavacomm`
https://search.maven.org/artifact/org.jetbrains.pty4j/pty4j/0.13.0/jar

**Closed by segrey** 2024-10-07 09:34 UTC
