### ISSUE TITLE
Maven artifact is broken

### ISSUE THREAD

**Issue by ajs1998** [JetBrains/pty4j#121] opened 2022-05-13 00:53 UTC
It looks like the `purejavacom` artifact that pty4j depends on doesn't exist anymore

```
Execution failed for task ':Main.main()'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find org.jetbrains.pty4j:purejavacomm:0.0.11.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/pty4j/purejavacomm/0.0.11.1/purejavacomm-0.0.11.1.pom
       - https://maven.pkg.github.com/ajs1998/Dag/org/jetbrains/pty4j/purejavacomm/0.0.11.1/purejavacomm-0.0.11.1.pom
     Required by:
         project : > org.jetbrains.pty4j:pty4j:0.12.7

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Not sure if this is a version bump issue or something

**Comment by satsen** [comment] 2022-09-07 20:22
Duplicate of #105 in which I already posted a workaround. Please close this.

**Closed** 2024-10-06 23:13 UTC
